const { app } = require('electron');
const path = require('path');
const fs = require('fs');
const fsp = fs.promises;
const files = require('./files');
const JSZip = require('jszip');

const results = [];
let rendererDone = null;

function t(name, ok, detail) {
  results.push({ name, ok: !!ok, detail: detail || '' });
  console.log(`SMOKE ${ok ? 'ok  ' : 'FAIL'} - ${name}${ok ? '' : ' :: ' + (detail || '')}`);
}

const SAMPLE_MD = `# Welcome to Margo

Margo reads and writes **Markdown**, *Word*, and Excel files.

## Features

- Live markdown preview
- Rich text editing
- Spreadsheet grid

| Item | Qty |
| --- | --- |
| Pens | 12 |

> Stay sharp.

\`\`\`js
console.log("hello margo");
\`\`\`
`;

async function backendTests(samplesDir, tmpDir) {
  // md -> docx
  let docxBuf = null;
  try {
    docxBuf = await files.htmlToDocxBuffer(files.markedParse(SAMPLE_MD), 'Welcome');
    t('backend: md -> docx buffer', docxBuf && docxBuf.length > 1000 && docxBuf[0] === 0x50 && docxBuf[1] === 0x4b,
      `len=${docxBuf ? docxBuf.length : 0}`);
  } catch (e) { t('backend: md -> docx buffer', false, e.message); }

  const sampleDocx = path.join(samplesDir, 'sample.docx');
  if (docxBuf) await fsp.writeFile(sampleDocx, docxBuf);

  // docx -> html via mammoth (round trip)
  try {
    const doc = await files.openPath(sampleDocx);
    const html = doc.html || '';
    t('backend: docx -> html (mammoth)', doc.kind === 'doc' && html.includes('Welcome to Margo') && html.includes('<'),
      html.slice(0, 120));
  } catch (e) { t('backend: docx -> html (mammoth)', false, e.message); }

  // html -> md via turndown
  try {
    const md = files.turndownHtml('<h2>Hi there</h2><ul><li>alpha</li><li>beta</li></ul><p><strong>bold</strong></p>');
    t('backend: html -> md (turndown)', md.includes('## Hi there') && /-\s+alpha/.test(md) && md.includes('**bold**'), md);
  } catch (e) { t('backend: html -> md (turndown)', false, e.message); }

  // xlsx write + read round trip
  const sampleXlsx = path.join(samplesDir, 'sample.xlsx');
  try {
    const model = {
      sheets: [
        { name: 'Budget', rows: [['Item', 'Qty', 'Price'], ['Pen', '2', '1.5'], ['Notebook', '1', '12'], ['Coffee', '3', '4.25']] },
        { name: 'Notes', rows: [['Margo says hi']] }
      ],
      active: 0
    };
    await files.save({ kind: 'sheet', path: sampleXlsx, data: model });
    const back = await files.openPath(sampleXlsx);
    const ok = back.kind === 'sheet'
      && back.sheets.length === 2
      && back.sheets[0].rows[1][0] === 'Pen'
      && back.sheets[0].rows[1][1] === '2'
      && back.sheets[0].rows[3][2] === '4.25'
      && back.sheets[1].rows[0][0] === 'Margo says hi';
    t('backend: xlsx write/read round trip', ok, JSON.stringify(back.sheets[0].rows[1] || []));
  } catch (e) { t('backend: xlsx write/read round trip', false, e.message); }

  // csv write + read round trip
  try {
    const csvPath = path.join(tmpDir, 'roundtrip.csv');
    await files.save({
      kind: 'sheet', path: csvPath,
      data: { sheets: [{ name: 'S', rows: [['a', 'b'], ['1', 'text with, comma']] }], active: 0 }
    });
    const back = await files.openPath(csvPath);
    const ok = back.sheets[0].rows[0][0] === 'a' && back.sheets[0].rows[1][1] === 'text with, comma';
    t('backend: csv write/read round trip', ok, JSON.stringify(back.sheets[0].rows));
  } catch (e) { t('backend: csv write/read round trip', false, e.message); }

  // md -> html document export
  try {
    const htmlPath = path.join(tmpDir, 'export.html');
    await files.save({ kind: 'md', path: htmlPath, data: { markdown: '# Export test' } });
    const txt = await fsp.readFile(htmlPath, 'utf8');
    t('backend: md -> html export', txt.includes('<h1') && txt.includes('Export test'));
  } catch (e) { t('backend: md -> html export', false, e.message); }

  // sample PDF with an embedded high-res image (for the viewer + extraction tests)
  try {
    const { PDFDocument, StandardFonts, rgb } = require('pdf-lib');
    const pdfDoc = await PDFDocument.create();
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const p1 = pdfDoc.addPage([612, 792]);
    p1.drawText('Margo sample PDF', { x: 60, y: 700, size: 26, font: bold, color: rgb(0.11, 0.11, 0.12) });
    p1.drawText('A two-page PDF with an embedded 512 px image, generated by the smoke suite.', {
      x: 60, y: 668, size: 12, font, color: rgb(0.35, 0.35, 0.38)
    });
    const iconBytes = fs.readFileSync(path.join(__dirname, '..', '..', 'assets', 'icon.png'));
    const png = await pdfDoc.embedPng(iconBytes);
    p1.drawImage(png, { x: 60, y: 370, width: 240, height: 240 });
    p1.drawText('Sign below:', { x: 60, y: 210, size: 12, font });
    p1.drawLine({ start: { x: 60, y: 160 }, end: { x: 300, y: 160 }, thickness: 1, color: rgb(0.6, 0.6, 0.6) });
    const p2 = pdfDoc.addPage([612, 792]);
    p2.drawText('Page two', { x: 60, y: 700, size: 20, font: bold });
    p2.drawText('Nothing to see here, just proving multi-page rendering works.', { x: 60, y: 670, size: 12, font });
    const bytes = await pdfDoc.save();
    await fsp.writeFile(path.join(samplesDir, 'sample.pdf'), bytes);
    t('backend: sample pdf generated (pdf-lib)', bytes.length > 5000);
  } catch (e) { t('backend: sample pdf generated (pdf-lib)', false, e.message); }

  try {
    const { PDFDocument } = require('pdf-lib');
    const blank = await PDFDocument.create();
    blank.addPage([612, 792]);
    const blankBytes = await blank.save();
    const blankPath = path.join(tmpDir, 'blank.pdf');
    await files.save({ kind: 'pdf', path: blankPath, data: { base64: Buffer.from(blankBytes).toString('base64') } });
    const opened = await files.openPath(blankPath);
    const reloaded = await PDFDocument.load(await fsp.readFile(blankPath));
    t('backend: blank pdf save/open', opened.kind === 'pdf' && reloaded.getPageCount() === 1 && blankBytes.length > 100,
      `kind=${opened && opened.kind} pages=${reloaded.getPageCount()} bytes=${blankBytes.length}`);
  } catch (e) { t('backend: blank pdf save/open', false, e.message); }

  // DOCX desktop thumbnail embed
  try {
    const tinyJpeg = Buffer.from(
      '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAn/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAX/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIQAxAAAAGcP//EABQQAQAAAAAAAAAAAAAAAAAAAAD/2gAIAQEAAQUCf//EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAIAQMBAT8Bf//EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAIAQIBAT8Bf//EABQQAQAAAAAAAAAAAAAAAAAAAAD/2gAIAQEABj8Cf//EABQQAQAAAAAAAAAAAAAAAAAAAAD/2gAIAQEAAT8hf//Z',
      'base64'
    );
    const base = await files.htmlToDocxBuffer('<p>Thumb embed</p>', 'Thumb');
    const withThumb = await files.embedDocxThumbnail(base, tinyJpeg, 'image/jpeg');
    const zip = await JSZip.loadAsync(withThumb);
    const entry = zip.file('docProps/thumbnail.jpeg');
    const ct = await zip.file('[Content_Types].xml').async('string');
    const rels = await zip.file('_rels/.rels').async('string');
    t('backend: docx thumbnail embed',
      !!entry && ct.includes('thumbnail.jpeg') && rels.includes('metadata/thumbnail'),
      `entry=${!!entry}`);
  } catch (e) { t('backend: docx thumbnail embed', false, e.message); }

  // Desktop file icons + associations config
  try {
    const root = path.join(__dirname, '..', '..');
    const kinds = ['md', 'doc', 'sheet', 'pdf'];
    const missing = kinds.filter((k) => !fs.existsSync(path.join(root, 'assets', 'file-icons', `${k}.ico`)));
    const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
    const assocs = (pkg.build && pkg.build.fileAssociations) || [];
    const hasMd = assocs.some((a) => [].concat(a.ext).includes('md'));
    const hasDocx = assocs.some((a) => [].concat(a.ext).includes('docx'));
    const hasXlsx = assocs.some((a) => [].concat(a.ext).includes('xlsx'));
    const hasPdf = assocs.some((a) => [].concat(a.ext).includes('pdf'));
    const perMachine = !!(pkg.build.nsis && pkg.build.nsis.perMachine);
    const iconsOk = assocs.every((a) => a.icon && a.icon.startsWith('file-icons/'));
    t('backend: file icons + associations',
      missing.length === 0 && hasMd && hasDocx && hasXlsx && hasPdf && perMachine && iconsOk,
      missing.length ? `missing ${missing.join(',')}` : `assocs=${assocs.length} perMachine=${perMachine}`);
  } catch (e) { t('backend: file icons + associations', false, e.message); }

  try {
    const drafts = require('./drafts');
    drafts.clear();
    const put = drafts.put({
      id: 'smoke-draft-1',
      kind: 'md',
      name: 'notes.md',
      path: null,
      updatedAt: Date.now(),
      data: { markdown: '# recovered' }
    });
    const listed = drafts.list();
    t('backend: drafts put/list', put && put.ok && listed.length === 1 && listed[0].data.markdown === '# recovered',
      `ok=${put && put.ok} n=${listed.length}`);
    drafts.remove('smoke-draft-1');
    t('backend: drafts remove', drafts.list().length === 0);
    drafts.put({ id: 'smoke-draft-2', kind: 'md', name: 'a.md', path: null, updatedAt: 1, data: { markdown: 'x' } });
    drafts.clear();
    t('backend: drafts clear', drafts.list().length === 0);
  } catch (e) { t('backend: drafts put/list', false, e.message); }
}

async function validateRendererArtifacts(tmpDir) {
  const read = (f) => fsp.readFile(path.join(tmpDir, f), 'utf8');
  try {
    const md = await read('ui-out.md');
    t('files: renderer-saved markdown has edit', md.includes('Smoke edit line.'));
  } catch (e) { t('files: renderer-saved markdown has edit', false, e.message); }

  try {
    const buf = await fsp.readFile(path.join(tmpDir, 'ui-export.docx'));
    t('files: renderer md -> docx export', buf.length > 800 && buf[0] === 0x50 && buf[1] === 0x4b);
  } catch (e) { t('files: renderer md -> docx export', false, e.message); }

  try {
    const md2 = await read('ui-doc-roundtrip.md');
    t('files: renderer doc -> md export', md2.includes('Doc smoke edit.'));
  } catch (e) { t('files: renderer doc -> md export', false, e.message); }

  try {
    const back = await files.openPath(path.join(tmpDir, 'ui-out.xlsx'));
    const ok = back.sheets[0].rows[0][0] === 'Changed by smoke' && back.sheets[0].rows[1][0] === 'Pen';
    t('files: renderer-saved xlsx (edit + intact data)', ok, JSON.stringify((back.sheets[0].rows || []).slice(0, 2)));
  } catch (e) { t('files: renderer-saved xlsx (edit + intact data)', false, e.message); }

  try {
    const csv = await read('ui-out.csv');
    t('files: renderer sheet -> csv export', csv.split(/\r?\n/)[0].includes('Changed by smoke'));
  } catch (e) { t('files: renderer sheet -> csv export', false, e.message); }

  try {
    const { PDFDocument } = require('pdf-lib');
    const orig = await fsp.readFile(path.join(__dirname, '..', '..', 'samples', 'sample.pdf'));
    const signed = await fsp.readFile(path.join(tmpDir, 'ui-signed.pdf'));
    const doc = await PDFDocument.load(signed);
    t('files: signed pdf valid, 2 pages, grew by signature',
      doc.getPageCount() === 2 && signed.length > orig.length,
      `orig=${orig.length} signed=${signed.length}`);
  } catch (e) { t('files: signed pdf valid, 2 pages, grew by signature', false, e.message); }

  try {
    const { PDFDocument } = require('pdf-lib');
    const checks = [];
    for (const f of ['export-md.pdf', 'export-doc.pdf', 'export-sheet.pdf']) {
      const buf = await fsp.readFile(path.join(tmpDir, f));
      const doc = await PDFDocument.load(buf);
      checks.push(`${f}:${doc.getPageCount()}p/${buf.length}b`);
      if (doc.getPageCount() < 1 || buf.length < 1500) throw new Error('suspicious ' + f);
    }
    t('files: pdf exports valid (md/doc/sheet)', true, checks.join(' '));
  } catch (e) { t('files: pdf exports valid (md/doc/sheet)', false, e.message); }

  try {
    const thumbsDirPath = path.join(app.getPath('userData'), 'thumbs');
    const pngs = fs.readdirSync(thumbsDirPath).filter((f) => f.endsWith('.png'));
    t('files: thumbnails persisted to disk', pngs.length >= 3, `${pngs.length} thumbs`);
  } catch (e) { t('files: thumbnails persisted to disk', false, e.message); }

  try {
    const docxPath = path.join(tmpDir, 'ui-out.docx');
    const buf = await fsp.readFile(docxPath);
    const zip = await JSZip.loadAsync(buf);
    const thumb = zip.file('docProps/thumbnail.jpeg') || zip.file('docProps/thumbnail.png');
    const size = thumb ? (await thumb.async('nodebuffer')).length : 0;
    t('files: saved docx embeds desktop thumbnail', !!thumb && size > 400, `size=${size}`);
  } catch (e) { t('files: saved docx embeds desktop thumbnail', false, e.message); }
}

async function run(win) {
  const samplesDir = path.join(__dirname, '..', '..', 'samples');
  const tmpDir = path.join(app.getPath('temp'), 'margo-smoke');
  fs.mkdirSync(samplesDir, { recursive: true });
  fs.rmSync(tmpDir, { recursive: true, force: true });
  fs.mkdirSync(tmpDir, { recursive: true });

  console.log('SMOKE start');
  await backendTests(samplesDir, tmpDir);

  // Renderer UI tests
  const rendererResults = await new Promise((resolve) => {
    rendererDone = resolve;
    win.webContents.send('smoke:run', {
      samplesDir,
      tmpDir,
      welcomePath: path.join(samplesDir, 'welcome.md'),
      docxPath: path.join(samplesDir, 'sample.docx'),
      xlsxPath: path.join(samplesDir, 'sample.xlsx'),
      pdfPath: path.join(samplesDir, 'sample.pdf')
    });
    setTimeout(() => resolve([{ name: 'ui: renderer responded', ok: false, detail: 'timeout after 90s' }]), 90000);
  });

  for (const r of rendererResults) {
    t(r.name, r.ok, r.detail);
  }

  await validateRendererArtifacts(tmpDir);

  const fails = results.filter((r) => !r.ok);
  console.log(`SMOKE done: ${results.length - fails.length}/${results.length} passed`);
  if (fails.length) console.log('SMOKE failures: ' + fails.map((f) => f.name).join(' | '));
  setTimeout(() => app.exit(fails.length ? 1 : 0), 400);
}

function onRendererReport(rendererResults) {
  if (rendererDone) {
    const done = rendererDone;
    rendererDone = null;
    done(Array.isArray(rendererResults) ? rendererResults : []);
  }
}

module.exports = { run, onRendererReport };
